<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "backend_ip_login"
 *
 * Auto generated by Extension Builder 2017-04-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Backend IP Auto Login',
    'description' => 'Remember access from ip masks and auto login to the backend.',
    'category' => 'services',
    'author' => 'Steffen Keuper',
    'author_email' => 'steffen.keuper@web.de',
    'state' => 'test',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
