services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SKeuper\BackendIpLogin\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  SKeuper\BackendIpLogin\Controller\MfaController:
    tags: [ 'backend.controller' ]
