services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  SKeuper\BackendIpLogin\Controller\MfaController:
    tags: ['backend.controller']
    public: true

  SKeuper\BackendIpLogin\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
